### ISSUE TITLE
No module named mrg

### ISSUE THREAD

**Issue by wsp666** [roberto-aldera/circular-motion-estimation#1]
The `mrg` module is not provided by pypi. Could you share your module? Thanks.

**Comment by roberto-aldera** [comment]
Hey @wsp666, the `mrg` module is part of the lab's internal code which isn't shared publicly, but it was only used here to parse the radar monolithic files so you should be able to swap that out for another component and still make use of the core code contained here. I'm not actively maintaining this but you're welcome to tinker with it!

**Comment by wsp666** [comment]
> 

Thanks.
